# Generated by Django 3.1.4 on 2021-08-22 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=200)),
                ('Question', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Stregthen_social_safety_nets', models.TextField(choices=[('Yes', 'Yes. Enact UBI (Universal Basic Income).'), ('Same', 'No. Spending levels as is'), ('Reduce', 'Negatory. Slowly stop funding Social Security')])),
                ('Nationalize_healthcare', models.TextField(choices=[('Yes', 'Yes. Nationalize it like the NHS in England.'), ('No', 'No. Leave it as is.')])),
                ('Climate_responce', models.TextField(choices=[('Strong', 'Take extraordinary measures. Enact enforceable laws to limit corprate and consumer enviromental impacts.'), ('Great', 'Take extraordinary measures. Enact enforceable laws to limit corprate enviromental impacts.'), ('Senseable', "Take oridnary meaures, don't tread on my consumption."), ('Capitalist', 'Take no meaures.')])),
                ('Should_we_limit_urban_sprall', models.TextField(choices=[('Yes', 'Yes. Promote city living.'), ('No', "No. Don't tread on me.")])),
                ('Do_you_support_or_oppose_globalization', models.TextField(choices=[('Yes', 'Yes. Globalization increases the quality of life and brings rich cultures together.'), ('No', 'No. We need to focuse on issued at home and let those people do the same. Things will work out better in the end.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('The_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.question')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
