# Generated by Django 3.1.13 on 2022-01-25 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question1', models.TextField(choices=[('not legitimate', 'These incidents are not legitimate. Perhaps it is a money grab by a bad faith defence agency.'), ('legitimate earthly', 'All UFOs must have earthly origin. The vastness of space is too grand for extraterrestrial life to make it. Perhaps they are from another state or non-state actor.'), ('legitimate earthly few extraterrestrial', 'Some UFOs have earthly origins, but accounts like Bob Lazar could possibly mean extraterrestrial origins.'), ('legitimate extraterrestrial', 'Bob Lazar and Captian David Fravor are not lying and extraterrestrial space crafts come into contact with earth.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
