# Generated by Django 3.1.4 on 2021-08-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='The_question',
            field=models.TextField(choices=[('Yes', 'Yes. Enact UBI (Universal Basic Income).'), ('Same', 'No. Spending levels as is'), ('Reduce', 'Negatory. Slowly stop funding Social Security')]),
        ),
    ]
