# Generated by Django 3.1.13 on 2021-11-14 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='Choice',
            new_name='choice',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='Text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='Title',
            new_name='title',
        ),
    ]
