# Generated by Django 3.1.13 on 2021-10-23 15:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20211017_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='Slug_Field',
            field=models.SlugField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='response',
            name='Question1',
            field=models.TextField(choices=[('Yes', 'Yes. I believe in determination'), ('No', 'No. I believe in self-determination.'), ('Maybe', 'I cant tell if there is fate, but maybe there is luck.'), ('Idk', 'I do not know.')]),
        ),
        migrations.AlterField(
            model_name='response',
            name='Question2',
            field=models.TextField(choices=[('Yes', 'Yes. My life had a meaning. I am here with a purpose.'), ('No', 'No. Life is random and lacks meaning.')]),
        ),
        migrations.AlterField(
            model_name='response',
            name='Question3',
            field=models.TextField(choices=[('Please God', "Appease God's will."), ('Panspermia', 'Spread life into the universe (a.k.a. panspermia).'), ('Persist', 'Preserve life on earth.'), ('Idealism', 'Uphold right and wrong.')]),
        ),
        migrations.AlterField(
            model_name='response',
            name='Question4',
            field=models.TextField(choices=[('Water', 'Water is a human right.'), ('Water, Food', 'Water and food are human rights.'), ('Water, Food, and Housing', 'Water, food, and housing are human rights.'), ('None', 'Nothing is guaranteed in life by others.')]),
        ),
        migrations.AlterField(
            model_name='response',
            name='Question5',
            field=models.TextField(choices=[('Humans', 'Humans using ancient building techquins and hard work.'), ('Alien Intervention', 'Humans with alien intervention.'), ('Divine Intervention', 'Humans with divine intervention.')]),
        ),
    ]
