# Generated by Django 3.1.13 on 2021-11-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20211114_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='question',
        ),
        migrations.RemoveField(
            model_name='response',
            name='response',
        ),
        migrations.AddField(
            model_name='response',
            name='Question1',
            field=models.TextField(choices=[('Yes', 'Yes. I believe in determination'), ('No', 'No. I believe in self-determination.'), ('Maybe', 'I cant tell if there is fate, but maybe there is luck.'), ('Idk', 'I do not know.')], default='Yes'),
        ),
        migrations.AddField(
            model_name='response',
            name='Question2',
            field=models.TextField(choices=[('Yes', 'Yes. My life had a meaning. I am here with a purpose.'), ('No', 'No. Life is random and lacks meaning.')], default='Yes'),
        ),
        migrations.AddField(
            model_name='response',
            name='Question3',
            field=models.TextField(choices=[('Please God', "Appease God's will."), ('Panspermia', 'Spread life into the universe (a.k.a. panspermia).'), ('Persist', 'Preserve life on earth.'), ('Idealism', 'Uphold right and wrong.')], default='Please God'),
        ),
        migrations.AddField(
            model_name='response',
            name='Question4',
            field=models.TextField(choices=[('Water', 'Water is a human right.'), ('Water, Food', 'Water and food are human rights.'), ('Water, Food, and Housing', 'Water, food, and housing are human rights.'), ('None', 'Nothing is guaranteed in life by others.')], default='Water'),
        ),
        migrations.AddField(
            model_name='response',
            name='Question5',
            field=models.TextField(choices=[('Humans', 'Humans using ancient building techquins and hard work.'), ('Alien Intervention', 'Humans with alien intervention.'), ('Divine Intervention', 'Humans with divine intervention.')], default='Humans'),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
