# Generated by Django 3.1.13 on 2022-03-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20220308_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='Question1',
            field=models.TextField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('Winter', 'Winter')]),
        ),
    ]
