# Generated by Django 3.1.4 on 2021-08-22 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210822_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='The_question',
        ),
    ]
