# Generated by Django 3.1.13 on 2021-11-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20211114_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='Question1',
            field=models.TextField(choices=[('Yes', 'Yes. I believe in determination'), ('No', 'No. I believe in self-determination.'), ('Maybe', 'I cant tell if there is fate, but maybe there is luck.'), ('Idk', 'I do not know.')]),
        ),
    ]
