# Generated by Django 3.1.13 on 2021-10-23 16:09

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20211023_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='Slug_Field',
            field=models.SlugField(default=accounts.models.CustomUser, max_length=200),
        ),
    ]
