# Generated by Django 3.1.13 on 2021-10-23 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20211023_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='Slug_Field',
        ),
    ]
