# Generated by Django 3.1.4 on 2021-08-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='Climate_responce',
            field=models.TextField(choices=[('Strong', 'Take extraordinary measures. Enact enforceable laws.'), ('Senseable', "Take oridnary meaures, don't tread on my consumption."), ('Capitalist', 'Take no meaures.')]),
        ),
    ]
