# Generated by Django 3.1.13 on 2021-10-08 17:25

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0004_auto_20211008_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='created_by',
            field=models.ForeignKey(default=accounts.models.CustomUser, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
