# Generated by Django 4.0 on 2021-12-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20211114_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='Question4',
            field=models.TextField(choices=[('Physiological', 'Physiological needs like food, water, sleep, shelter.'), ('Safety', 'Security of body, employment, resources, health.'), ('Education conditional', 'You are allowed unlimited education if you are qualified.'), ('Education unconditional', 'Unlimited free education.')]),
        ),
        migrations.AlterField(
            model_name='response',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
