# Generated by Django 3.1.4 on 2021-08-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20210822_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='Do_you_support_or_oppose_globalization',
            field=models.TextField(choices=[('Yes', 'Yes. Globalization increases the quality of life and brings rich cultures together.'), ('No', 'No. We need to focuse on issued at home. Things will work out better in the end.')]),
        ),
    ]
